'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');

const {
  MANIFEST_PATH,
  RULE_FILENAMES,
  VERSION_PATH,
  managedPathToAbsolute,
  toPosixPath,
  validateManagedPath,
} = require('./paths');

const { version: PACKAGE_VERSION } = require('../package.json');
const SCHEMA_VERSION = 1;
const DEFAULT_SOURCE_ROOT = path.resolve(__dirname, '..');
const MANAGED_YAML_COMMENT =
  '# BOFFIN-MANAGED: generated by boffinit; local edits may be replaced.';
const MANAGED_HTML_COMMENT =
  '<!-- BOFFIN-MANAGED: generated by boffinit; local edits may be replaced. -->';

function isMissing(error) {
  return error && error.code === 'ENOENT';
}

async function lstatIfExists(filePath) {
  try {
    return await fs.lstat(filePath);
  } catch (error) {
    if (isMissing(error)) {
      return null;
    }
    throw error;
  }
}

function rewritePackReferences(content) {
  return content.replace(/(^|[^\w./-])packs\//gm, '$1.boffin/packs/');
}

function generateManagedRule(content) {
  let generated = rewritePackReferences(content);
  if (generated.includes('BOFFIN-MANAGED: generated by boffinit')) {
    return generated;
  }

  const eol = generated.includes('\r\n') ? '\r\n' : '\n';
  const frontmatterStart = `---${eol}`;
  if (generated.startsWith(frontmatterStart)) {
    generated = `${frontmatterStart}${MANAGED_YAML_COMMENT}${eol}${generated.slice(frontmatterStart.length)}`;
  } else {
    generated = `${MANAGED_HTML_COMMENT}${eol}${generated}`;
  }
  return generated;
}

function validateManifest(manifest) {
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    throw new Error('manifest root must be an object');
  }
  if (manifest.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`unsupported schemaVersion ${String(manifest.schemaVersion)}; expected 1`);
  }
  if (typeof manifest.version !== 'string' || manifest.version.length === 0) {
    throw new Error('version must be a non-empty string');
  }
  if (manifest.installMethod !== 'cursor') {
    throw new Error('installMethod must be "cursor"');
  }
  if (
    typeof manifest.installedAt !== 'string'
    || Number.isNaN(Date.parse(manifest.installedAt))
  ) {
    throw new Error('installedAt must be an ISO date string');
  }
  if (!Array.isArray(manifest.managedFiles)) {
    throw new Error('managedFiles must be an array');
  }

  const managedFiles = manifest.managedFiles.map(validateManagedPath);
  if (new Set(managedFiles).size !== managedFiles.length) {
    throw new Error('managedFiles must not contain duplicates');
  }

  return {
    schemaVersion: SCHEMA_VERSION,
    version: manifest.version,
    installMethod: 'cursor',
    installedAt: manifest.installedAt,
    managedFiles,
  };
}

async function readManifest(target) {
  const manifestFile = managedPathToAbsolute(target, MANIFEST_PATH);
  const stat = await lstatIfExists(manifestFile);
  if (!stat) {
    return null;
  }
  if (!stat.isFile()) {
    throw new Error(`Invalid boffinit manifest at ${manifestFile}: expected a regular file`);
  }

  let parsed;
  try {
    parsed = JSON.parse(await fs.readFile(manifestFile, 'utf8'));
  } catch (error) {
    throw new Error(`Invalid boffinit manifest at ${manifestFile}: ${error.message}`);
  }

  try {
    return validateManifest(parsed);
  } catch (error) {
    throw new Error(`Invalid boffinit manifest at ${manifestFile}: ${error.message}`);
  }
}

async function listTreeFiles(root, relativeDirectory = '') {
  const directory = relativeDirectory
    ? path.join(root, ...relativeDirectory.split('/'))
    : root;
  const entries = await fs.readdir(directory, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));

  const files = [];
  for (const entry of entries) {
    const relativePath = relativeDirectory
      ? `${relativeDirectory}/${entry.name}`
      : entry.name;
    if (entry.isDirectory()) {
      files.push(...await listTreeFiles(root, relativePath));
    } else if (entry.isFile() || entry.isSymbolicLink()) {
      files.push(relativePath);
    } else {
      throw new Error(`Unsupported source pack entry: ${relativePath}`);
    }
  }
  return files;
}

async function copyEntry(source, destination) {
  const stat = await fs.lstat(source);
  if (stat.isDirectory()) {
    await fs.mkdir(destination, { recursive: true });
    const entries = await fs.readdir(source, { withFileTypes: true });
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      await copyEntry(
        path.join(source, entry.name),
        path.join(destination, entry.name),
      );
    }
    return;
  }

  await fs.mkdir(path.dirname(destination), { recursive: true });
  if (stat.isFile()) {
    await fs.copyFile(source, destination);
    return;
  }
  if (stat.isSymbolicLink()) {
    const linkTarget = await fs.readlink(source);
    let linkType;
    if (process.platform === 'win32') {
      const targetStat = await fs.stat(source);
      linkType = targetStat.isDirectory() ? 'junction' : 'file';
    }
    await fs.symlink(linkTarget, destination, linkType);
    return;
  }
  throw new Error(`Unsupported filesystem entry: ${source}`);
}

async function treeHasUnknownFiles(
  existingDirectory,
  relativeDirectory,
  previousManagedFiles,
) {
  const entries = await fs.readdir(existingDirectory, { withFileTypes: true });
  for (const entry of entries) {
    const relativePath = relativeDirectory
      ? `${relativeDirectory}/${entry.name}`
      : entry.name;
    if (entry.isDirectory()) {
      if (await treeHasUnknownFiles(
        path.join(existingDirectory, entry.name),
        relativePath,
        previousManagedFiles,
      )) {
        return true;
      }
    } else if (!previousManagedFiles.has(`.boffin/packs/${relativePath}`)) {
      return true;
    }
  }
  return false;
}

async function mergeUnknownPackFiles(
  existingDirectory,
  stagedDirectory,
  previousManagedFiles,
  relativeDirectory = '',
) {
  const existingStat = await lstatIfExists(existingDirectory);
  if (!existingStat) {
    return;
  }
  if (!existingStat.isDirectory()) {
    throw new Error(
      `Cannot replace ${existingDirectory}: expected a directory; move it aside and retry`,
    );
  }

  const entries = await fs.readdir(existingDirectory, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    const relativePath = relativeDirectory
      ? `${relativeDirectory}/${entry.name}`
      : entry.name;
    const existingPath = path.join(existingDirectory, entry.name);
    const stagedPath = path.join(stagedDirectory, entry.name);
    const managedPath = `.boffin/packs/${relativePath}`;
    const stagedStat = await lstatIfExists(stagedPath);

    if (entry.isDirectory()) {
      if (stagedStat && !stagedStat.isDirectory()) {
        if (await treeHasUnknownFiles(existingPath, relativePath, previousManagedFiles)) {
          throw new Error(
            `Cannot install managed pack file ${managedPath}; it would replace unknown files`,
          );
        }
        continue;
      }
      await fs.mkdir(stagedPath, { recursive: true });
      await mergeUnknownPackFiles(
        existingPath,
        stagedPath,
        previousManagedFiles,
        relativePath,
      );
      continue;
    }

    if (previousManagedFiles.has(managedPath)) {
      continue;
    }
    if (stagedStat) {
      throw new Error(
        `Cannot install managed pack file ${managedPath}; an unknown file already exists`,
      );
    }
    await copyEntry(existingPath, stagedPath);
  }
}

async function removeEmptyDirectories(directory, removeRoot = false) {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      await removeEmptyDirectories(path.join(directory, entry.name), true);
    }
  }

  if (removeRoot && (await fs.readdir(directory)).length === 0) {
    await fs.rmdir(directory);
  }
}

async function loadInstallSource(sourceRoot) {
  const packsDirectory = path.join(sourceRoot, 'packs');
  const packsStat = await lstatIfExists(packsDirectory);
  if (!packsStat || !packsStat.isDirectory()) {
    throw new Error(`Installer source is missing its packs directory: ${packsDirectory}`);
  }

  const packFiles = await listTreeFiles(packsDirectory);
  if (packFiles.length === 0) {
    throw new Error(`Installer source contains no pack files: ${packsDirectory}`);
  }

  const rules = new Map();
  for (const filename of RULE_FILENAMES) {
    const sourceFile = path.join(sourceRoot, '.cursor', 'rules', filename);
    const sourceStat = await lstatIfExists(sourceFile);
    if (!sourceStat || !sourceStat.isFile()) {
      throw new Error(`Installer source is missing Cursor rule: ${sourceFile}`);
    }
    rules.set(filename, generateManagedRule(await fs.readFile(sourceFile, 'utf8')));
  }

  return {
    packFiles,
    packsDirectory,
    rules,
  };
}

function buildManagedFiles(packFiles) {
  return [
    ...packFiles.map((file) => `.boffin/packs/${toPosixPath(file)}`),
    VERSION_PATH,
    MANIFEST_PATH,
    ...RULE_FILENAMES.map((filename) => `.cursor/rules/${filename}`),
  ].sort();
}

function createManifest(managedFiles, previousManifest, now) {
  const installedAt = previousManifest
    ? previousManifest.installedAt
    : now().toISOString();
  return {
    schemaVersion: SCHEMA_VERSION,
    version: PACKAGE_VERSION,
    installMethod: 'cursor',
    installedAt,
    managedFiles,
  };
}

async function assertDirectoryOrMissing(directory, label) {
  const stat = await lstatIfExists(directory);
  if (stat && !stat.isDirectory()) {
    throw new Error(`${label} must be a directory: ${directory}`);
  }
  return stat;
}

async function removeDirectoryIfEmpty(directory) {
  try {
    await fs.rmdir(directory);
  } catch (error) {
    if (!isMissing(error) && error.code !== 'ENOTEMPTY' && error.code !== 'EEXIST') {
      throw error;
    }
  }
}

async function captureFile(filePath, label) {
  const stat = await lstatIfExists(filePath);
  if (!stat) {
    return { exists: false, content: null };
  }
  if (!stat.isFile()) {
    throw new Error(`${label} must be a regular file: ${filePath}`);
  }
  return { exists: true, content: await fs.readFile(filePath) };
}

async function writeFileAtomic(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const token = crypto.randomBytes(6).toString('hex');
  const temporary = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.boffinit-${process.pid}-${token}.tmp`,
  );

  try {
    await fs.writeFile(temporary, content, { flag: 'wx' });
    await fs.rename(temporary, filePath);
  } finally {
    await fs.rm(temporary, { force: true }).catch(() => {});
  }
}

async function restoreFile(filePath, snapshot) {
  if (snapshot.exists) {
    await writeFileAtomic(filePath, snapshot.content);
  } else {
    await fs.rm(filePath, { force: true });
  }
}

async function applyInstall(action, options = {}) {
  const {
    target,
    dryRun = false,
    sourceRoot = DEFAULT_SOURCE_ROOT,
    now = () => new Date(),
  } = options;
  if (!target) {
    throw new Error('A target path is required');
  }

  const resolvedTarget = path.resolve(target);
  const previousManifest = await readManifest(resolvedTarget);
  if (action === 'update' && !previousManifest) {
    throw new Error(
      `No boffinit installation found at ${resolvedTarget}; run "boffinit cursor install --target <path>" first`,
    );
  }

  const source = await loadInstallSource(path.resolve(sourceRoot));
  const managedFiles = buildManagedFiles(source.packFiles);
  const manifest = createManifest(managedFiles, previousManifest, now);

  if (dryRun) {
    return {
      action,
      changed: false,
      dryRun: true,
      managedFiles,
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  const targetExisted = Boolean(
    await assertDirectoryOrMissing(resolvedTarget, 'Target'),
  );
  const boffinDirectory = path.join(resolvedTarget, '.boffin');
  const cursorDirectory = path.join(resolvedTarget, '.cursor');
  const rulesDirectory = path.join(cursorDirectory, 'rules');
  const livePacks = path.join(boffinDirectory, 'packs');
  const boffinExisted = Boolean(
    await assertDirectoryOrMissing(boffinDirectory, '.boffin'),
  );
  const cursorExisted = Boolean(
    await assertDirectoryOrMissing(cursorDirectory, '.cursor'),
  );
  const rulesExisted = Boolean(
    await assertDirectoryOrMissing(rulesDirectory, '.cursor/rules'),
  );
  await assertDirectoryOrMissing(livePacks, '.boffin/packs');

  const versionFile = managedPathToAbsolute(resolvedTarget, VERSION_PATH);
  const manifestFile = managedPathToAbsolute(resolvedTarget, MANIFEST_PATH);
  const snapshots = new Map();
  snapshots.set(versionFile, await captureFile(versionFile, 'Installed VERSION'));
  for (const filename of RULE_FILENAMES) {
    const ruleFile = path.join(rulesDirectory, filename);
    snapshots.set(ruleFile, await captureFile(ruleFile, 'Cursor rule'));
  }

  await fs.mkdir(boffinDirectory, { recursive: true });
  const temporaryRoot = await fs.mkdtemp(path.join(boffinDirectory, '.boffinit-tmp-'));
  const stagedPacks = path.join(temporaryRoot, 'packs');
  const previousManagedFiles = new Set(previousManifest?.managedFiles ?? []);
  let backupPacks = null;
  let packsPublished = false;
  let preserveTemporary = false;
  let succeeded = false;
  const publishedFiles = [];

  try {
    await copyEntry(source.packsDirectory, stagedPacks);
    await mergeUnknownPackFiles(
      livePacks,
      stagedPacks,
      previousManagedFiles,
    );
    await removeEmptyDirectories(stagedPacks);

    if (await lstatIfExists(livePacks)) {
      backupPacks = path.join(temporaryRoot, 'previous-packs');
      await fs.rename(livePacks, backupPacks);
    }

    try {
      await fs.rename(stagedPacks, livePacks);
      packsPublished = true;
    } catch (error) {
      if (backupPacks) {
        await fs.rename(backupPacks, livePacks);
        backupPacks = null;
      }
      throw error;
    }

    await writeFileAtomic(versionFile, `${PACKAGE_VERSION}\n`);
    publishedFiles.push(versionFile);
    for (const [filename, content] of source.rules) {
      const ruleFile = path.join(rulesDirectory, filename);
      await writeFileAtomic(ruleFile, content);
      publishedFiles.push(ruleFile);
    }

    await writeFileAtomic(
      manifestFile,
      `${JSON.stringify(manifest, null, 2)}\n`,
    );
    succeeded = true;
  } catch (error) {
    const rollbackErrors = [];
    for (const filePath of publishedFiles.reverse()) {
      try {
        await restoreFile(filePath, snapshots.get(filePath));
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError.message);
      }
    }

    let canRestoreBackup = !packsPublished;
    if (packsPublished) {
      try {
        await fs.rm(livePacks, { recursive: true, force: true });
        packsPublished = false;
        canRestoreBackup = true;
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError.message);
      }
    }
    if (backupPacks && await lstatIfExists(backupPacks)) {
      if (canRestoreBackup) {
        try {
          await fs.rename(backupPacks, livePacks);
          backupPacks = null;
        } catch (rollbackError) {
          rollbackErrors.push(rollbackError.message);
        }
      }
      if (backupPacks) {
        preserveTemporary = true;
        rollbackErrors.push(`previous pack tree preserved at ${backupPacks}`);
      }
    }

    if (rollbackErrors.length > 0) {
      error.message += `; rollback also failed: ${rollbackErrors.join('; ')}`;
    }
    throw error;
  } finally {
    if (!preserveTemporary) {
      await fs.rm(temporaryRoot, { recursive: true, force: true }).catch(() => {});
    }
    if (!succeeded) {
      if (!rulesExisted) {
        await removeDirectoryIfEmpty(rulesDirectory).catch(() => {});
      }
      if (!cursorExisted) {
        await removeDirectoryIfEmpty(cursorDirectory).catch(() => {});
      }
      if (!boffinExisted) {
        await removeDirectoryIfEmpty(boffinDirectory).catch(() => {});
      }
      if (!targetExisted) {
        await removeDirectoryIfEmpty(resolvedTarget).catch(() => {});
      }
    }
  }

  return {
    action,
    changed: true,
    dryRun: false,
    managedFiles,
    target: resolvedTarget,
    version: PACKAGE_VERSION,
  };
}

async function install(options) {
  return applyInstall('install', options);
}

async function update(options) {
  return applyInstall('update', options);
}

async function removeEmptyManagedDirectories(target, managedFiles) {
  const directories = new Set();
  for (const managedFile of managedFiles) {
    let current = path.dirname(managedPathToAbsolute(target, managedFile));
    while (current !== target) {
      directories.add(current);
      const parent = path.dirname(current);
      if (parent === current) {
        break;
      }
      current = parent;
    }
  }

  const deepestFirst = [...directories].sort(
    (left, right) => right.split(path.sep).length - left.split(path.sep).length,
  );
  for (const directory of deepestFirst) {
    try {
      await fs.rmdir(directory);
    } catch (error) {
      if (!isMissing(error) && error.code !== 'ENOTEMPTY' && error.code !== 'EEXIST') {
        throw error;
      }
    }
  }
}

async function uninstall(options = {}) {
  const { target, dryRun = false } = options;
  if (!target) {
    throw new Error('A target path is required');
  }

  const resolvedTarget = path.resolve(target);
  const manifest = await readManifest(resolvedTarget);
  if (!manifest) {
    return {
      action: 'uninstall',
      changed: false,
      dryRun,
      managedFiles: [],
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  const managedFiles = [...new Set([...manifest.managedFiles, MANIFEST_PATH])];
  for (const managedFile of managedFiles) {
    const filePath = managedPathToAbsolute(resolvedTarget, managedFile);
    const stat = await lstatIfExists(filePath);
    if (stat && !stat.isFile() && !stat.isSymbolicLink()) {
      throw new Error(
        `Refusing to uninstall because a managed file became a directory: ${filePath}`,
      );
    }
  }

  if (dryRun) {
    return {
      action: 'uninstall',
      changed: false,
      dryRun: true,
      managedFiles,
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  for (const managedFile of managedFiles) {
    if (managedFile === MANIFEST_PATH) {
      continue;
    }
    await fs.rm(managedPathToAbsolute(resolvedTarget, managedFile), { force: true });
  }
  await fs.rm(managedPathToAbsolute(resolvedTarget, MANIFEST_PATH), { force: true });
  await removeEmptyManagedDirectories(resolvedTarget, managedFiles);

  return {
    action: 'uninstall',
    changed: true,
    dryRun: false,
    managedFiles,
    target: resolvedTarget,
    version: PACKAGE_VERSION,
  };
}

module.exports = {
  PACKAGE_VERSION,
  SCHEMA_VERSION,
  generateManagedRule,
  install,
  readManifest,
  rewritePackReferences,
  uninstall,
  update,
  validateManifest,
};
