'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');

const {
  BOFFIN_AGENTS_PATH,
  MANIFEST_PATH,
  OPENCODE_INSTRUCTION,
  OPENCODE_MANIFEST_PATH,
  PROFILE_PATH,
  RULE_FILENAMES,
  VERSION_PATH,
  managedPathToAbsolute,
  openCodeManagedPathToAbsolute,
  projectPathToAbsolute,
  toPosixPath,
  validateManagedPath,
  validateOpenCodeManagedPath,
} = require('./paths');
const {
  BOFFIN_COMMAND,
  BOFFIN_REVIEW_COMMAND,
  BOFFIN_REVIEW_SKILL,
  BOFFIN_SKILL,
  JSONC_SKIP_NOTE,
  OPENCODE_MANAGED_FILES,
} = require('./opencode-templates');

const { version: PACKAGE_VERSION } = require('../package.json');
const SCHEMA_VERSION = 1;
const DEFAULT_SOURCE_ROOT = path.resolve(__dirname, '..');
const MANAGED_YAML_COMMENT =
  '# BOFFIN-MANAGED: generated by boffinit; local edits may be replaced.';
const MANAGED_HTML_COMMENT =
  '<!-- BOFFIN-MANAGED: generated by boffinit; local edits may be replaced. -->';
const INSTALL_ROOT_LINE =
  'Boffin install root: `.boffin/` in this project. Resolve contract `packs/...` paths against `.boffin/packs/...`.';

function isMissing(error) {
  return error && error.code === 'ENOENT';
}

async function lstatIfExists(filePath) {
  try {
    return await fs.lstat(filePath);
  } catch (error) {
    if (isMissing(error)) {
      return null;
    }
    throw error;
  }
}

async function pathExists(filePath) {
  return Boolean(await lstatIfExists(filePath));
}

function rewritePackReferences(content) {
  return content.replace(/(^|[^\w./-])packs\//gm, '$1.boffin/packs/');
}

function generateManagedRule(content) {
  let generated = rewritePackReferences(content);
  if (generated.includes('BOFFIN-MANAGED: generated by boffinit')) {
    return generated;
  }

  const eol = generated.includes('\r\n') ? '\r\n' : '\n';
  const frontmatterStart = `---${eol}`;
  if (generated.startsWith(frontmatterStart)) {
    generated = `${frontmatterStart}${MANAGED_YAML_COMMENT}${eol}${generated.slice(frontmatterStart.length)}`;
  } else {
    generated = `${MANAGED_HTML_COMMENT}${eol}${generated}`;
  }
  return generated;
}

function generateBoffinAgents(content) {
  const rewritten = rewritePackReferences(content);
  const eol = rewritten.includes('\r\n') ? '\r\n' : '\n';
  return `${MANAGED_HTML_COMMENT}${eol}${INSTALL_ROOT_LINE}${eol}${eol}${rewritten}`;
}

function validateManifest(manifest) {
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    throw new Error('manifest root must be an object');
  }
  if (manifest.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`unsupported schemaVersion ${String(manifest.schemaVersion)}; expected 1`);
  }
  if (typeof manifest.version !== 'string' || manifest.version.length === 0) {
    throw new Error('version must be a non-empty string');
  }
  if (manifest.installMethod !== 'cursor') {
    throw new Error('installMethod must be "cursor"');
  }
  if (
    typeof manifest.installedAt !== 'string'
    || Number.isNaN(Date.parse(manifest.installedAt))
  ) {
    throw new Error('installedAt must be an ISO date string');
  }
  if (!Array.isArray(manifest.managedFiles)) {
    throw new Error('managedFiles must be an array');
  }

  const managedFiles = manifest.managedFiles.map(validateManagedPath);
  if (new Set(managedFiles).size !== managedFiles.length) {
    throw new Error('managedFiles must not contain duplicates');
  }

  return {
    schemaVersion: SCHEMA_VERSION,
    version: manifest.version,
    installMethod: 'cursor',
    installedAt: manifest.installedAt,
    managedFiles,
  };
}

function validateOpenCodeManifest(manifest) {
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    throw new Error('manifest root must be an object');
  }
  if (manifest.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`unsupported schemaVersion ${String(manifest.schemaVersion)}; expected 1`);
  }
  if (typeof manifest.version !== 'string' || manifest.version.length === 0) {
    throw new Error('version must be a non-empty string');
  }
  if (manifest.installMethod !== 'opencode') {
    throw new Error('installMethod must be "opencode"');
  }
  if (
    typeof manifest.installedAt !== 'string'
    || Number.isNaN(Date.parse(manifest.installedAt))
  ) {
    throw new Error('installedAt must be an ISO date string');
  }
  if (!Array.isArray(manifest.managedFiles)) {
    throw new Error('managedFiles must be an array');
  }

  const managedFiles = manifest.managedFiles.map(validateOpenCodeManagedPath);
  if (new Set(managedFiles).size !== managedFiles.length) {
    throw new Error('managedFiles must not contain duplicates');
  }

  let opencodeConfig = null;
  if (manifest.opencodeConfig !== undefined && manifest.opencodeConfig !== null) {
    if (
      typeof manifest.opencodeConfig !== 'object'
      || Array.isArray(manifest.opencodeConfig)
    ) {
      throw new Error('opencodeConfig must be an object');
    }
    if (manifest.opencodeConfig.path !== 'opencode.json') {
      throw new Error('opencodeConfig.path must be "opencode.json"');
    }
    if (typeof manifest.opencodeConfig.created !== 'boolean') {
      throw new Error('opencodeConfig.created must be a boolean');
    }
    if (manifest.opencodeConfig.instruction !== OPENCODE_INSTRUCTION) {
      throw new Error(`opencodeConfig.instruction must be "${OPENCODE_INSTRUCTION}"`);
    }
    opencodeConfig = {
      path: 'opencode.json',
      created: manifest.opencodeConfig.created,
      instruction: OPENCODE_INSTRUCTION,
    };
  }

  return {
    schemaVersion: SCHEMA_VERSION,
    version: manifest.version,
    installMethod: 'opencode',
    installedAt: manifest.installedAt,
    managedFiles,
    boffinAgents: BOFFIN_AGENTS_PATH,
    profileFile: PROFILE_PATH,
    opencodeConfig,
  };
}

async function readManifest(target) {
  const manifestFile = managedPathToAbsolute(target, MANIFEST_PATH);
  const stat = await lstatIfExists(manifestFile);
  if (!stat) {
    return null;
  }
  if (!stat.isFile()) {
    throw new Error(`Invalid boffinit manifest at ${manifestFile}: expected a regular file`);
  }

  let parsed;
  try {
    parsed = JSON.parse(await fs.readFile(manifestFile, 'utf8'));
  } catch (error) {
    throw new Error(`Invalid boffinit manifest at ${manifestFile}: ${error.message}`);
  }

  try {
    return validateManifest(parsed);
  } catch (error) {
    throw new Error(`Invalid boffinit manifest at ${manifestFile}: ${error.message}`);
  }
}

async function readOpenCodeManifest(target) {
  const manifestFile = openCodeManagedPathToAbsolute(target, OPENCODE_MANIFEST_PATH);
  const stat = await lstatIfExists(manifestFile);
  if (!stat) {
    return null;
  }
  if (!stat.isFile()) {
    throw new Error(
      `Invalid boffinit OpenCode manifest at ${manifestFile}: expected a regular file`,
    );
  }

  let parsed;
  try {
    parsed = JSON.parse(await fs.readFile(manifestFile, 'utf8'));
  } catch (error) {
    throw new Error(
      `Invalid boffinit OpenCode manifest at ${manifestFile}: ${error.message}`,
    );
  }

  try {
    return validateOpenCodeManifest(parsed);
  } catch (error) {
    throw new Error(
      `Invalid boffinit OpenCode manifest at ${manifestFile}: ${error.message}`,
    );
  }
}

async function listTreeFiles(root, relativeDirectory = '') {
  const directory = relativeDirectory
    ? path.join(root, ...relativeDirectory.split('/'))
    : root;
  const entries = await fs.readdir(directory, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));

  const files = [];
  for (const entry of entries) {
    const relativePath = relativeDirectory
      ? `${relativeDirectory}/${entry.name}`
      : entry.name;
    if (entry.isDirectory()) {
      files.push(...await listTreeFiles(root, relativePath));
    } else if (entry.isFile() || entry.isSymbolicLink()) {
      files.push(relativePath);
    } else {
      throw new Error(`Unsupported source pack entry: ${relativePath}`);
    }
  }
  return files;
}

async function copyEntry(source, destination) {
  const stat = await fs.lstat(source);
  if (stat.isDirectory()) {
    await fs.mkdir(destination, { recursive: true });
    const entries = await fs.readdir(source, { withFileTypes: true });
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      await copyEntry(
        path.join(source, entry.name),
        path.join(destination, entry.name),
      );
    }
    return;
  }

  await fs.mkdir(path.dirname(destination), { recursive: true });
  if (stat.isFile()) {
    await fs.copyFile(source, destination);
    return;
  }
  if (stat.isSymbolicLink()) {
    const linkTarget = await fs.readlink(source);
    let linkType;
    if (process.platform === 'win32') {
      const targetStat = await fs.stat(source);
      linkType = targetStat.isDirectory() ? 'junction' : 'file';
    }
    await fs.symlink(linkTarget, destination, linkType);
    return;
  }
  throw new Error(`Unsupported filesystem entry: ${source}`);
}

async function treeHasUnknownFiles(
  existingDirectory,
  relativeDirectory,
  previousManagedFiles,
) {
  const entries = await fs.readdir(existingDirectory, { withFileTypes: true });
  for (const entry of entries) {
    const relativePath = relativeDirectory
      ? `${relativeDirectory}/${entry.name}`
      : entry.name;
    if (entry.isDirectory()) {
      if (await treeHasUnknownFiles(
        path.join(existingDirectory, entry.name),
        relativePath,
        previousManagedFiles,
      )) {
        return true;
      }
    } else if (!previousManagedFiles.has(`.boffin/packs/${relativePath}`)) {
      return true;
    }
  }
  return false;
}

async function mergeUnknownPackFiles(
  existingDirectory,
  stagedDirectory,
  previousManagedFiles,
  relativeDirectory = '',
) {
  const existingStat = await lstatIfExists(existingDirectory);
  if (!existingStat) {
    return;
  }
  if (!existingStat.isDirectory()) {
    throw new Error(
      `Cannot replace ${existingDirectory}: expected a directory; move it aside and retry`,
    );
  }

  const entries = await fs.readdir(existingDirectory, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    const relativePath = relativeDirectory
      ? `${relativeDirectory}/${entry.name}`
      : entry.name;
    const existingPath = path.join(existingDirectory, entry.name);
    const stagedPath = path.join(stagedDirectory, entry.name);
    const managedPath = `.boffin/packs/${relativePath}`;
    const stagedStat = await lstatIfExists(stagedPath);

    if (entry.isDirectory()) {
      if (stagedStat && !stagedStat.isDirectory()) {
        if (await treeHasUnknownFiles(existingPath, relativePath, previousManagedFiles)) {
          throw new Error(
            `Cannot install managed pack file ${managedPath}; it would replace unknown files`,
          );
        }
        continue;
      }
      await fs.mkdir(stagedPath, { recursive: true });
      await mergeUnknownPackFiles(
        existingPath,
        stagedPath,
        previousManagedFiles,
        relativePath,
      );
      continue;
    }

    if (previousManagedFiles.has(managedPath)) {
      continue;
    }
    if (stagedStat) {
      throw new Error(
        `Cannot install managed pack file ${managedPath}; an unknown file already exists`,
      );
    }
    await copyEntry(existingPath, stagedPath);
  }
}

async function removeEmptyDirectories(directory, removeRoot = false) {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      await removeEmptyDirectories(path.join(directory, entry.name), true);
    }
  }

  if (removeRoot && (await fs.readdir(directory)).length === 0) {
    // Best-effort prune: if a concurrent writer refilled the directory or it is
    // already gone, leave it rather than failing an otherwise-clean publish.
    try {
      await fs.rmdir(directory);
    } catch (error) {
      if (!isMissing(error) && error.code !== 'ENOTEMPTY' && error.code !== 'EEXIST') {
        throw error;
      }
    }
  }
}

async function loadPackSource(sourceRoot) {
  const packsDirectory = path.join(sourceRoot, 'packs');
  const packsStat = await lstatIfExists(packsDirectory);
  if (!packsStat || !packsStat.isDirectory()) {
    throw new Error(`Installer source is missing its packs directory: ${packsDirectory}`);
  }

  const packFiles = await listTreeFiles(packsDirectory);
  if (packFiles.length === 0) {
    throw new Error(`Installer source contains no pack files: ${packsDirectory}`);
  }

  return {
    packFiles,
    packsDirectory,
  };
}

async function loadInstallSource(sourceRoot) {
  const packs = await loadPackSource(sourceRoot);
  const rules = new Map();
  for (const filename of RULE_FILENAMES) {
    const sourceFile = path.join(sourceRoot, '.cursor', 'rules', filename);
    const sourceStat = await lstatIfExists(sourceFile);
    if (!sourceStat || !sourceStat.isFile()) {
      throw new Error(`Installer source is missing Cursor rule: ${sourceFile}`);
    }
    rules.set(filename, generateManagedRule(await fs.readFile(sourceFile, 'utf8')));
  }

  return {
    ...packs,
    rules,
  };
}

async function loadOpenCodeSource(sourceRoot) {
  const packs = await loadPackSource(sourceRoot);
  const agentsSource = path.join(sourceRoot, 'AGENTS.md');
  const agentsStat = await lstatIfExists(agentsSource);
  if (!agentsStat || !agentsStat.isFile()) {
    throw new Error(`Installer source is missing AGENTS.md: ${agentsSource}`);
  }

  return {
    ...packs,
    agentsContent: generateBoffinAgents(await fs.readFile(agentsSource, 'utf8')),
    commands: new Map([
      ['boffin.md', `${BOFFIN_COMMAND.trimEnd()}\n`],
      ['boffin-review.md', `${BOFFIN_REVIEW_COMMAND.trimEnd()}\n`],
    ]),
    skills: new Map([
      ['boffin/SKILL.md', `${BOFFIN_SKILL.trimEnd()}\n`],
      ['boffin-review/SKILL.md', `${BOFFIN_REVIEW_SKILL.trimEnd()}\n`],
    ]),
  };
}

function buildManagedFiles(packFiles) {
  return [
    ...packFiles.map((file) => `.boffin/packs/${toPosixPath(file)}`),
    VERSION_PATH,
    MANIFEST_PATH,
    ...RULE_FILENAMES.map((filename) => `.cursor/rules/${filename}`),
  ].sort();
}

function createManifest(managedFiles, previousManifest, now) {
  const installedAt = previousManifest
    ? previousManifest.installedAt
    : now().toISOString();
  return {
    schemaVersion: SCHEMA_VERSION,
    version: PACKAGE_VERSION,
    installMethod: 'cursor',
    installedAt,
    managedFiles,
  };
}

function createOpenCodeManifest(previousManifest, now, opencodeConfig) {
  const installedAt = previousManifest
    ? previousManifest.installedAt
    : now().toISOString();
  const manifest = {
    schemaVersion: SCHEMA_VERSION,
    version: PACKAGE_VERSION,
    installMethod: 'opencode',
    installedAt,
    managedFiles: [...OPENCODE_MANAGED_FILES],
    boffinAgents: BOFFIN_AGENTS_PATH,
    profileFile: PROFILE_PATH,
  };
  if (opencodeConfig) {
    manifest.opencodeConfig = opencodeConfig;
  }
  return manifest;
}

async function assertDirectoryOrMissing(directory, label) {
  const stat = await lstatIfExists(directory);
  if (stat && !stat.isDirectory()) {
    throw new Error(`${label} must be a directory: ${directory}`);
  }
  return stat;
}

async function removeDirectoryIfEmpty(directory) {
  try {
    await fs.rmdir(directory);
  } catch (error) {
    if (!isMissing(error) && error.code !== 'ENOTEMPTY' && error.code !== 'EEXIST') {
      throw error;
    }
  }
}

async function captureFile(filePath, label) {
  const stat = await lstatIfExists(filePath);
  if (!stat) {
    return { exists: false, content: null };
  }
  if (!stat.isFile()) {
    throw new Error(`${label} must be a regular file: ${filePath}`);
  }
  return { exists: true, content: await fs.readFile(filePath) };
}

async function writeFileAtomic(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const token = crypto.randomBytes(6).toString('hex');
  const temporary = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.boffinit-${process.pid}-${token}.tmp`,
  );

  try {
    await fs.writeFile(temporary, content, { flag: 'wx' });
    await fs.rename(temporary, filePath);
  } finally {
    await fs.rm(temporary, { force: true }).catch(() => {});
  }
}

async function restoreFile(filePath, snapshot) {
  if (snapshot.exists) {
    await writeFileAtomic(filePath, snapshot.content);
  } else {
    await fs.rm(filePath, { force: true });
  }
}

async function resolvePreviousPackManagedFiles(resolvedTarget, packFiles, knownPackManifest) {
  const previousManagedFiles = new Set(
    (knownPackManifest?.managedFiles ?? []).filter((file) => file.startsWith('.boffin/packs/')),
  );

  // With a manifest that lists packs (Cursor), trust its list so an incomplete
  // manifest still trips the unknown-file conflict guard. Without one, treat
  // on-disk packs that overlap the source tree as replaceable, since both hosts
  // vendor byte-identical packs for the same boffinit version.
  if (knownPackManifest) {
    return previousManagedFiles;
  }

  const livePacks = path.join(resolvedTarget, '.boffin', 'packs');
  for (const file of packFiles) {
    const relative = toPosixPath(file);
    const absolute = path.join(livePacks, ...relative.split('/'));
    if (await lstatIfExists(absolute)) {
      previousManagedFiles.add(`.boffin/packs/${relative}`);
    }
  }
  return previousManagedFiles;
}

function isSharedManagedPath(managedFile) {
  return managedFile === VERSION_PATH || managedFile.startsWith('.boffin/packs/');
}

function normalizeInstructionEntry(value) {
  if (typeof value !== 'string') {
    return null;
  }
  let normalized = toPosixPath(value).trim();
  while (normalized.startsWith('./')) {
    normalized = normalized.slice(2);
  }
  return path.posix.normalize(normalized);
}

async function mergeOpenCodeConfig(resolvedTarget, previousConfig = null) {
  const configPath = path.join(resolvedTarget, 'opencode.json');
  const jsoncPath = path.join(resolvedTarget, 'opencode.jsonc');
  const configStat = await lstatIfExists(configPath);
  const jsoncStat = await lstatIfExists(jsoncPath);

  if (!configStat && jsoncStat) {
    return {
      ok: false,
      note: JSONC_SKIP_NOTE,
      opencodeConfig: null,
    };
  }

  let created = false;
  let parsed;

  if (!configStat) {
    created = true;
    parsed = {};
  } else {
    // Preserve first-install ownership so uninstall can still delete a file we created.
    created = previousConfig?.created === true;
    if (!configStat.isFile()) {
      return {
        ok: false,
        note: `Skipped opencode.json: ${configPath} is not a regular file`,
        opencodeConfig: null,
      };
    }
    try {
      parsed = JSON.parse(await fs.readFile(configPath, 'utf8'));
    } catch (error) {
      return {
        ok: false,
        note: `Skipped opencode.json: parse failed (${error.message})`,
        opencodeConfig: null,
      };
    }
  }

  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return {
      ok: false,
      note: 'Skipped opencode.json: root must be a JSON object',
      opencodeConfig: null,
    };
  }

  if (!Object.hasOwn(parsed, '$schema')) {
    parsed.$schema = 'https://opencode.ai/config.json';
  }

  if (!Object.hasOwn(parsed, 'instructions')) {
    parsed.instructions = [];
  } else if (!Array.isArray(parsed.instructions)) {
    return {
      ok: false,
      note: 'Skipped opencode.json: "instructions" must be an array',
      opencodeConfig: null,
    };
  }

  const alreadyPresent = parsed.instructions.some(
    (entry) => normalizeInstructionEntry(entry) === OPENCODE_INSTRUCTION,
  );
  if (!alreadyPresent) {
    parsed.instructions.push(OPENCODE_INSTRUCTION);
  }

  await writeFileAtomic(configPath, `${JSON.stringify(parsed, null, 2)}\n`);
  return {
    ok: true,
    note: null,
    opencodeConfig: {
      path: 'opencode.json',
      created,
      instruction: OPENCODE_INSTRUCTION,
    },
  };
}

async function reverseOpenCodeConfig(resolvedTarget, opencodeConfig) {
  if (!opencodeConfig) {
    return;
  }

  const configPath = path.join(resolvedTarget, opencodeConfig.path);
  const stat = await lstatIfExists(configPath);
  if (!stat || !stat.isFile()) {
    return;
  }

  let parsed;
  try {
    parsed = JSON.parse(await fs.readFile(configPath, 'utf8'));
  } catch {
    return;
  }

  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return;
  }

  if (Array.isArray(parsed.instructions)) {
    parsed.instructions = parsed.instructions.filter(
      (entry) => normalizeInstructionEntry(entry) !== opencodeConfig.instruction,
    );
  }

  const keys = Object.keys(parsed);
  const onlySchema = keys.length === 1 && keys[0] === '$schema';
  const onlyEmptyInstructions = keys.length === 1
    && keys[0] === 'instructions'
    && Array.isArray(parsed.instructions)
    && parsed.instructions.length === 0;
  const onlySchemaAndEmptyInstructions = keys.length === 2
    && Object.hasOwn(parsed, '$schema')
    && Object.hasOwn(parsed, 'instructions')
    && Array.isArray(parsed.instructions)
    && parsed.instructions.length === 0;

  if (
    opencodeConfig.created
    && (keys.length === 0 || onlySchema || onlyEmptyInstructions || onlySchemaAndEmptyInstructions)
  ) {
    await fs.rm(configPath, { force: true });
    return;
  }

  if (!opencodeConfig.created && keys.length === 0) {
    await writeFileAtomic(configPath, '{}\n');
    return;
  }

  await writeFileAtomic(configPath, `${JSON.stringify(parsed, null, 2)}\n`);
}

// Publishes the shared `.boffin/packs` tree rebuild-then-swap style and returns a
// handle to either commit (drop the temp/backup) or roll back to the prior tree.
// Owns only the packs tree and its temp scratch; the caller owns VERSION, its own
// managed files, and all directory teardown so ownership and ordering stay local.
async function publishSharedPacks(options) {
  const {
    resolvedTarget,
    packsDirectory,
    packFiles,
    knownPackManifest,
    boffinDirectory,
  } = options;

  const livePacks = path.join(boffinDirectory, 'packs');
  await assertDirectoryOrMissing(livePacks, '.boffin/packs');
  const previousManagedFiles = await resolvePreviousPackManagedFiles(
    resolvedTarget,
    packFiles,
    knownPackManifest,
  );

  await fs.mkdir(boffinDirectory, { recursive: true });
  const temporaryRoot = await fs.mkdtemp(path.join(boffinDirectory, '.boffinit-tmp-'));
  const stagedPacks = path.join(temporaryRoot, 'packs');
  let backupPacks = null;
  let packsPublished = false;

  try {
    await copyEntry(packsDirectory, stagedPacks);
    await mergeUnknownPackFiles(livePacks, stagedPacks, previousManagedFiles);
    await removeEmptyDirectories(stagedPacks);

    if (await lstatIfExists(livePacks)) {
      backupPacks = path.join(temporaryRoot, 'previous-packs');
      await fs.rename(livePacks, backupPacks);
    }

    try {
      await fs.rename(stagedPacks, livePacks);
      packsPublished = true;
    } catch (error) {
      if (backupPacks) {
        await fs.rename(backupPacks, livePacks);
        backupPacks = null;
      }
      throw error;
    }
  } catch (error) {
    await fs.rm(temporaryRoot, { recursive: true, force: true }).catch(() => {});
    throw error;
  }

  return {
    async commit() {
      await fs.rm(temporaryRoot, { recursive: true, force: true }).catch(() => {});
    },
    async rollback(rollbackErrors) {
      let canRestoreBackup = !packsPublished;
      if (packsPublished) {
        try {
          await fs.rm(livePacks, { recursive: true, force: true });
          packsPublished = false;
          canRestoreBackup = true;
        } catch (rollbackError) {
          rollbackErrors.push(rollbackError.message);
        }
      }
      let preserved = false;
      if (backupPacks && await lstatIfExists(backupPacks)) {
        if (canRestoreBackup) {
          try {
            await fs.rename(backupPacks, livePacks);
            backupPacks = null;
          } catch (rollbackError) {
            rollbackErrors.push(rollbackError.message);
          }
        }
        if (backupPacks) {
          preserved = true;
          rollbackErrors.push(`previous pack tree preserved at ${backupPacks}`);
        }
      }
      if (!preserved) {
        await fs.rm(temporaryRoot, { recursive: true, force: true }).catch(() => {});
      }
    },
  };
}

async function applyInstall(action, options = {}) {
  const {
    target,
    dryRun = false,
    sourceRoot = DEFAULT_SOURCE_ROOT,
    now = () => new Date(),
  } = options;
  if (!target) {
    throw new Error('A target path is required');
  }

  const resolvedTarget = path.resolve(target);
  const previousManifest = await readManifest(resolvedTarget);
  if (action === 'update' && !previousManifest) {
    throw new Error(
      `No boffinit installation found at ${resolvedTarget}; run "boffinit cursor install --target <path>" first`,
    );
  }

  const source = await loadInstallSource(path.resolve(sourceRoot));
  const managedFiles = buildManagedFiles(source.packFiles);
  const manifest = createManifest(managedFiles, previousManifest, now);

  if (dryRun) {
    return {
      action,
      changed: false,
      dryRun: true,
      managedFiles,
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  const targetExisted = Boolean(
    await assertDirectoryOrMissing(resolvedTarget, 'Target'),
  );
  const boffinDirectory = path.join(resolvedTarget, '.boffin');
  const cursorDirectory = path.join(resolvedTarget, '.cursor');
  const rulesDirectory = path.join(cursorDirectory, 'rules');
  const boffinExisted = Boolean(
    await assertDirectoryOrMissing(boffinDirectory, '.boffin'),
  );
  const cursorExisted = Boolean(
    await assertDirectoryOrMissing(cursorDirectory, '.cursor'),
  );
  const rulesExisted = Boolean(
    await assertDirectoryOrMissing(rulesDirectory, '.cursor/rules'),
  );

  const manifestFile = managedPathToAbsolute(resolvedTarget, MANIFEST_PATH);
  const versionFile = managedPathToAbsolute(resolvedTarget, VERSION_PATH);
  const snapshots = new Map();
  snapshots.set(versionFile, await captureFile(versionFile, 'Installed VERSION'));
  for (const filename of RULE_FILENAMES) {
    const ruleFile = path.join(rulesDirectory, filename);
    snapshots.set(ruleFile, await captureFile(ruleFile, 'Cursor rule'));
  }

  let packPublish;
  const publishedFiles = [];
  let succeeded = false;

  try {
    packPublish = await publishSharedPacks({
      resolvedTarget,
      packsDirectory: source.packsDirectory,
      packFiles: source.packFiles,
      knownPackManifest: previousManifest,
      boffinDirectory,
    });
    await writeFileAtomic(versionFile, `${PACKAGE_VERSION}\n`);
    publishedFiles.push(versionFile);

    for (const [filename, content] of source.rules) {
      const ruleFile = path.join(rulesDirectory, filename);
      await writeFileAtomic(ruleFile, content);
      publishedFiles.push(ruleFile);
    }

    await writeFileAtomic(
      manifestFile,
      `${JSON.stringify(manifest, null, 2)}\n`,
    );
    succeeded = true;
  } catch (error) {
    const rollbackErrors = [];
    for (const filePath of publishedFiles.reverse()) {
      try {
        await restoreFile(filePath, snapshots.get(filePath));
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError.message);
      }
    }
    if (packPublish) {
      await packPublish.rollback(rollbackErrors);
    }
    if (rollbackErrors.length > 0) {
      error.message += `; rollback also failed: ${rollbackErrors.join('; ')}`;
    }
    throw error;
  } finally {
    if (packPublish && succeeded) {
      await packPublish.commit();
    }
    if (!succeeded) {
      if (!rulesExisted) {
        await removeDirectoryIfEmpty(rulesDirectory).catch(() => {});
      }
      if (!cursorExisted) {
        await removeDirectoryIfEmpty(cursorDirectory).catch(() => {});
      }
      if (!boffinExisted) {
        await removeDirectoryIfEmpty(boffinDirectory).catch(() => {});
      }
      if (!targetExisted) {
        await removeDirectoryIfEmpty(resolvedTarget).catch(() => {});
      }
    }
  }

  return {
    action,
    changed: true,
    dryRun: false,
    managedFiles,
    target: resolvedTarget,
    version: PACKAGE_VERSION,
  };
}

async function applyOpenCodeInstall(action, options = {}) {
  const {
    target,
    dryRun = false,
    sourceRoot = DEFAULT_SOURCE_ROOT,
    now = () => new Date(),
  } = options;
  if (!target) {
    throw new Error('A target path is required');
  }

  const resolvedTarget = path.resolve(target);
  const previousManifest = await readOpenCodeManifest(resolvedTarget);
  if (action === 'update' && !previousManifest) {
    throw new Error(
      `No boffinit OpenCode installation found at ${resolvedTarget}; run "boffinit opencode install --target <path>" first`,
    );
  }

  const source = await loadOpenCodeSource(path.resolve(sourceRoot));
  const managedFiles = [...OPENCODE_MANAGED_FILES];

  if (dryRun) {
    return {
      action,
      changed: false,
      dryRun: true,
      host: 'opencode',
      managedFiles,
      notes: [],
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  const targetExisted = Boolean(
    await assertDirectoryOrMissing(resolvedTarget, 'Target'),
  );
  const boffinDirectory = path.join(resolvedTarget, '.boffin');
  const openCodeDirectory = path.join(resolvedTarget, '.opencode');
  const skillsDirectory = path.join(openCodeDirectory, 'skills');
  const commandsDirectory = path.join(openCodeDirectory, 'commands');
  const boffinExisted = Boolean(
    await assertDirectoryOrMissing(boffinDirectory, '.boffin'),
  );
  const openCodeExisted = Boolean(
    await assertDirectoryOrMissing(openCodeDirectory, '.opencode'),
  );
  const skillsExisted = Boolean(
    await assertDirectoryOrMissing(skillsDirectory, '.opencode/skills'),
  );
  const commandsExisted = Boolean(
    await assertDirectoryOrMissing(commandsDirectory, '.opencode/commands'),
  );

  const agentsFile = openCodeManagedPathToAbsolute(resolvedTarget, BOFFIN_AGENTS_PATH);
  const profileFile = openCodeManagedPathToAbsolute(resolvedTarget, PROFILE_PATH);
  const manifestFile = openCodeManagedPathToAbsolute(resolvedTarget, OPENCODE_MANIFEST_PATH);
  const versionFile = openCodeManagedPathToAbsolute(resolvedTarget, VERSION_PATH);
  const configPath = path.join(resolvedTarget, 'opencode.json');
  const snapshots = new Map();
  snapshots.set(versionFile, await captureFile(versionFile, 'Installed VERSION'));
  snapshots.set(agentsFile, await captureFile(agentsFile, 'Boffin AGENTS.md'));
  snapshots.set(profileFile, await captureFile(profileFile, 'Boffin profile'));
  snapshots.set(configPath, await captureFile(configPath, 'opencode.json'));
  for (const managedFile of OPENCODE_MANAGED_FILES) {
    const absolute = openCodeManagedPathToAbsolute(resolvedTarget, managedFile);
    snapshots.set(absolute, await captureFile(absolute, 'OpenCode managed file'));
  }

  const notes = [];
  let packPublish;
  const publishedFiles = [];
  let configResult = { ok: false, note: null, opencodeConfig: null };
  let configWritten = false;
  let succeeded = false;

  try {
    packPublish = await publishSharedPacks({
      resolvedTarget,
      packsDirectory: source.packsDirectory,
      packFiles: source.packFiles,
      knownPackManifest: null,
      boffinDirectory,
    });
    await writeFileAtomic(versionFile, `${PACKAGE_VERSION}\n`);
    publishedFiles.push(versionFile);

    await writeFileAtomic(agentsFile, source.agentsContent);
    publishedFiles.push(agentsFile);

    if (!(await lstatIfExists(profileFile))) {
      await writeFileAtomic(profileFile, 'full\n');
      publishedFiles.push(profileFile);
    }

    for (const [relative, content] of source.skills) {
      const skillFile = path.join(skillsDirectory, ...relative.split('/'));
      await writeFileAtomic(skillFile, content);
      publishedFiles.push(skillFile);
    }
    for (const [filename, content] of source.commands) {
      const commandFile = path.join(commandsDirectory, filename);
      await writeFileAtomic(commandFile, content);
      publishedFiles.push(commandFile);
    }

    configResult = await mergeOpenCodeConfig(
      resolvedTarget,
      previousManifest?.opencodeConfig ?? null,
    );
    if (configResult.note) {
      notes.push(configResult.note);
    }
    if (configResult.ok) {
      configWritten = true;
    }

    const manifest = createOpenCodeManifest(
      previousManifest,
      now,
      configResult.opencodeConfig,
    );
    await writeFileAtomic(
      manifestFile,
      `${JSON.stringify(manifest, null, 2)}\n`,
    );
    succeeded = true;
  } catch (error) {
    const rollbackErrors = [];
    for (const filePath of publishedFiles.reverse()) {
      try {
        await restoreFile(filePath, snapshots.get(filePath) ?? { exists: false, content: null });
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError.message);
      }
    }
    if (configWritten) {
      try {
        await restoreFile(configPath, snapshots.get(configPath));
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError.message);
      }
    }
    if (packPublish) {
      await packPublish.rollback(rollbackErrors);
    }
    if (rollbackErrors.length > 0) {
      error.message += `; rollback also failed: ${rollbackErrors.join('; ')}`;
    }
    throw error;
  } finally {
    if (packPublish && succeeded) {
      await packPublish.commit();
    }
    if (!succeeded) {
      if (!commandsExisted) {
        await removeDirectoryIfEmpty(commandsDirectory).catch(() => {});
      }
      if (!skillsExisted) {
        await removeDirectoryIfEmpty(skillsDirectory).catch(() => {});
      }
      if (!openCodeExisted) {
        await removeDirectoryIfEmpty(openCodeDirectory).catch(() => {});
      }
      if (!boffinExisted) {
        await removeDirectoryIfEmpty(boffinDirectory).catch(() => {});
      }
      if (!targetExisted) {
        await removeDirectoryIfEmpty(resolvedTarget).catch(() => {});
      }
    }
  }

  return {
    action,
    changed: true,
    dryRun: false,
    host: 'opencode',
    managedFiles,
    notes,
    opencodeConfig: configResult.opencodeConfig,
    target: resolvedTarget,
    version: PACKAGE_VERSION,
  };
}

async function install(options) {
  return applyInstall('install', options);
}

async function update(options) {
  return applyInstall('update', options);
}

async function installOpenCode(options) {
  return applyOpenCodeInstall('install', options);
}

async function updateOpenCode(options) {
  return applyOpenCodeInstall('update', options);
}

async function removeEmptyManagedDirectories(target, managedFiles) {
  const resolvedTarget = path.resolve(target);
  const directories = new Set();
  for (const managedFile of managedFiles) {
    let current = path.dirname(projectPathToAbsolute(resolvedTarget, managedFile));
    while (current !== resolvedTarget) {
      directories.add(current);
      const parent = path.dirname(current);
      if (parent === current) {
        break;
      }
      current = parent;
    }
  }

  const deepestFirst = [...directories].sort(
    (left, right) => right.split(path.sep).length - left.split(path.sep).length,
  );
  for (const directory of deepestFirst) {
    try {
      await fs.rmdir(directory);
    } catch (error) {
      if (!isMissing(error) && error.code !== 'ENOTEMPTY' && error.code !== 'EEXIST') {
        throw error;
      }
    }
  }
}

async function uninstall(options = {}) {
  const { target, dryRun = false } = options;
  if (!target) {
    throw new Error('A target path is required');
  }

  const resolvedTarget = path.resolve(target);
  const manifest = await readManifest(resolvedTarget);
  if (!manifest) {
    return {
      action: 'uninstall',
      changed: false,
      dryRun,
      managedFiles: [],
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  const keepShared = await pathExists(
    projectPathToAbsolute(resolvedTarget, OPENCODE_MANIFEST_PATH),
  );
  const managedFiles = [...new Set([...manifest.managedFiles, MANIFEST_PATH])];
  const filesToRemove = managedFiles.filter((managedFile) => {
    if (managedFile === MANIFEST_PATH) {
      return true;
    }
    if (keepShared && isSharedManagedPath(managedFile)) {
      return false;
    }
    return true;
  });

  for (const managedFile of filesToRemove) {
    const filePath = managedPathToAbsolute(resolvedTarget, managedFile);
    const stat = await lstatIfExists(filePath);
    if (stat && !stat.isFile() && !stat.isSymbolicLink()) {
      throw new Error(
        `Refusing to uninstall because a managed file became a directory: ${filePath}`,
      );
    }
  }

  if (dryRun) {
    return {
      action: 'uninstall',
      changed: false,
      dryRun: true,
      managedFiles: filesToRemove,
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  for (const managedFile of filesToRemove) {
    if (managedFile === MANIFEST_PATH) {
      continue;
    }
    await fs.rm(managedPathToAbsolute(resolvedTarget, managedFile), { force: true });
  }
  await fs.rm(managedPathToAbsolute(resolvedTarget, MANIFEST_PATH), { force: true });
  await removeEmptyManagedDirectories(resolvedTarget, filesToRemove);

  return {
    action: 'uninstall',
    changed: true,
    dryRun: false,
    managedFiles: filesToRemove,
    target: resolvedTarget,
    version: PACKAGE_VERSION,
  };
}

async function uninstallOpenCode(options = {}) {
  const { target, dryRun = false } = options;
  if (!target) {
    throw new Error('A target path is required');
  }

  const resolvedTarget = path.resolve(target);
  const manifest = await readOpenCodeManifest(resolvedTarget);
  if (!manifest) {
    return {
      action: 'uninstall',
      changed: false,
      dryRun,
      host: 'opencode',
      managedFiles: [],
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  const keepShared = await pathExists(
    projectPathToAbsolute(resolvedTarget, MANIFEST_PATH),
  );
  const managedFiles = [...new Set([
    ...manifest.managedFiles,
    BOFFIN_AGENTS_PATH,
    PROFILE_PATH,
    OPENCODE_MANIFEST_PATH,
  ])];
  for (const managedFile of managedFiles) {
    const filePath = openCodeManagedPathToAbsolute(resolvedTarget, managedFile);
    const stat = await lstatIfExists(filePath);
    if (stat && !stat.isFile() && !stat.isSymbolicLink()) {
      throw new Error(
        `Refusing to uninstall because a managed file became a directory: ${filePath}`,
      );
    }
  }

  if (dryRun) {
    return {
      action: 'uninstall',
      changed: false,
      dryRun: true,
      host: 'opencode',
      managedFiles,
      target: resolvedTarget,
      version: PACKAGE_VERSION,
    };
  }

  for (const managedFile of managedFiles) {
    if (managedFile === OPENCODE_MANIFEST_PATH) {
      continue;
    }
    await fs.rm(openCodeManagedPathToAbsolute(resolvedTarget, managedFile), {
      force: true,
    });
  }

  await reverseOpenCodeConfig(resolvedTarget, manifest.opencodeConfig);

  if (!keepShared) {
    const packsDirectory = path.join(resolvedTarget, '.boffin', 'packs');
    const versionFile = projectPathToAbsolute(resolvedTarget, VERSION_PATH);
    await fs.rm(packsDirectory, { recursive: true, force: true });
    await fs.rm(versionFile, { force: true });
  }

  await fs.rm(openCodeManagedPathToAbsolute(resolvedTarget, OPENCODE_MANIFEST_PATH), {
    force: true,
  });

  const cleanupPaths = [
    ...managedFiles,
    ...(keepShared ? [] : [VERSION_PATH]),
  ];
  await removeEmptyManagedDirectories(resolvedTarget, cleanupPaths);

  return {
    action: 'uninstall',
    changed: true,
    dryRun: false,
    host: 'opencode',
    managedFiles,
    target: resolvedTarget,
    version: PACKAGE_VERSION,
  };
}

module.exports = {
  PACKAGE_VERSION,
  SCHEMA_VERSION,
  generateBoffinAgents,
  generateManagedRule,
  install,
  installOpenCode,
  readManifest,
  readOpenCodeManifest,
  rewritePackReferences,
  uninstall,
  uninstallOpenCode,
  update,
  updateOpenCode,
  validateManifest,
  validateOpenCodeManifest,
};
